version: '3.7'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=edge
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - './postgres-data/volume/bk:/bk'
      - './postgres-data/volume/data:/var/lib/postgresql/data'
    networks:
      - internal-network-postgres-db
  app:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
      - '3000:3000'

    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/edge?schema=public
      - JWT_SECRET=batman

    depends_on:
      postgres-db:
        condition: service_started
    links:
      - postgres-db
    networks:
      - internal-network-postgres-db
volumes:
  postgres-data:
networks:
  internal-network-postgres-db:
    driver: bridge
