version: '3.7'
services:
  postgres-test-db:
    container_name: postgres-test-db
    image: postgres:alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=test
    logging:
        options:
          max-size: 10m
          max-file: "3"
    networks:
      - network-test-db

networks:
  network-test-db:
    driver: bridge