name: Running tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_TEST_URL: postgresql://postgres:docker@localhost:5433/test?schema=test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yarn

    - name: Build and run PostgreSQL
      run: |
        docker-compose up -d
    
    - name: Run server-nestjs tests
      run: |
        yarn test:server-nestjs

    - name: Run server-nestjs e2e tests
      run: |
        yarn test:server-nestjs:e2e

    - name: Stop PostgreSQL container
      run: |
        docker-compose down