name: Running tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: batman

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yarn

    - name: Docker compose up
      run: |
        docker-compose -f docker-compose-test.yml up -d
    
    - name: Run client tests
      run: |
        yarn test:client
    
    - name: Run server-nestjs unit tests
      run: |
        yarn test:server-nestjs

    - name: Run server-nestjs e2e tests
      run: |
        yarn test:server-nestjs:e2e

    - name: Docker compose down
      run: |
        docker-compose -f docker-compose-test.yml down